# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{custom-class-objects}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["hiroeorz"]
  s.date = %q{2010-10-13}
  s.email = %q{hiroe.orz@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "custom-class-objects.gemspec",
     "lib/custom_class_objects.rb",
     "lib/custom_class_objects/ext_nil.rb",
     "lib/custom_class_objects/ext_object.rb",
     "lib/custom_class_objects/ext_string.rb",
     "lib/custom_class_objects/ext_time.rb",
     "spec/custom-class-objects_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/hiroeorz/custom-class-objects}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{todo is not exist}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/custom-class-objects_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

